### ISSUE TITLE
Add CI to the repository

### ISSUE THREAD

**Issue by brentleyjones** [TabletopAssistant/DiceKit#12]
Do any have Xcode 7 support already? I want one that is always cutting edge.

**Comment by brentleyjones** [comment]
Seems like Travis CI has support, just not available to the public yet. Circle CI is currently evaluating it.

I would rather not have to run an Xcode Bots instance somewhere. Maybe it will be best since it can cover all of TabletopAssistant's repos.

**Comment by brentleyjones** [comment]
[Bitrise](https://www.bitrise.io) has Xcode 7 (currently beta 2 from last weekend, but beta 3 this weekend, so hopefully they will stay up to date quickly). I have it up and running, let's see how it handles the next pull request.

**Comment by brentleyjones** [comment]
As can be seen in #19 the CI is working. I don't believe the logs are publicly accessible though, which will probably be a deal breaker (though better than nothing until another solution comes along). I've tweeted them asking about this though.

**Comment by brentleyjones** [comment]
Update on this: Beta 3 is now working through Bitrise, which means our tests are working. I've requested open logs, but it will probably be a while. Their free tier is limited to 200 builds a month, which isn't that much when each push kicks off a build and each PR update does as well. The next tier up is $29/mo with unlimited builds.

TravisCI on the other hand is 100% free for open source, but currently doesn't have Xcode 7 beta. Come September that won't matter though.

Hmm...

**Comment by JonathanHoffman** [comment]
Sounds like a choice between $30 a month and Xcode support. I promise to do my part and push as little code as possible per month. ;)

**Comment by brentleyjones** [comment]
I wouldn't worry about it. I reached out to Bitwise and they said they would give us unlimited builds. When that happens I'll close this issue.

**Comment by brentleyjones** [comment]
Bitrise came through! Unlimited builds. I hope they implement open logs soon, but for now we are going with them.

**Comment by LoganJohnson** [comment]
Very nice!
