### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by brentleyjones** [TabletopAssistant/DiceKit#17]
Sort of important...

**Comment by brentleyjones** [comment]
I'm thinking Apache 2.0 (https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) or MIT (https://tldrlegal.com/license/mit-license).

@TabletopAssistant/dicekit?

**Comment by brentleyjones** [comment]
In particular, I think that section 5 of Apache 2.0 means we don't need a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement):

> 1. Submission of Contributions. Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions. Notwithstanding the above, nothing herein shall supersede or modify the terms of any separate license agreement you may have executed with Licensor regarding such Contributions.

Well, not needed if we don't plan on making it commercially available as well... _I think_.

My vote is for Apache 2.0, if no one is against it.

**Comment by LoganJohnson** [comment]
In my quick look at it I didn't see anything that swayed me hard in either direction. Apache seems a little more formal but not in a bad way. I'm good with Apache 2.0.

**Comment by JonathanHoffman** [comment]
I always liked the straightforwardness of MIT. But I don't think I have a strong enough opinion to push either way, so if you think Apache 2.0 is best then I would go with that.
