### ISSUE TITLE
Add usage section to Readme

### ISSUE THREAD

**Issue by brentleyjones** [TabletopAssistant/DiceKit#31]

**Comment by brentleyjones** [comment]
@TabletopAssistant/dicekit do we think this is needed for [0.1 release](https://github.com/TabletopAssistant/DiceKit/milestones/0.1:%20It%20Starts%20with%20a%20Single%20Die)?

**Comment by JonathanHoffman** [comment]
Probably not "needed." But since we do have some usable functionality I don't think it would be a bad idea. Also, the way .1 is defined makes it sound like that it should have at least a rough usage section.

**Comment by brentleyjones** [comment]
At least a rough one, yeah. I think I'll also do a quick and dirty playground as well, to set a precedence (#37).

**Comment by LoganJohnson** [comment]
Agreed on that.
