### ISSUE TITLE
Support CocoaPods

### ISSUE THREAD

**Issue by brentleyjones** [TabletopAssistant/DiceKit#5]
When we do the `.podspec` let's make sure that it requires the least amount of maintenance possible. This will also possibly warrant a way to test that the podspec works correctly, an integration test of some sort.

**Comment by brentleyjones** [comment]
I'm not sure if I want to support CocoaPods. I'm personally against it myself, this will be a niche framework, and it will be really easy to integrate without CocoaPods.

Thoughts @TabletopAssistant/dicekit?

**Comment by LoganJohnson** [comment]
I'm cool with that. I don't think it will be an issue. It can always be done later if the need presents itself for some reason.

**Comment by JonathanHoffman** [comment]
Sounds like we are too far ahead of ourselves on this one, shelf it for later.
