### ISSUE TITLE
Add CustomStringConvertible and CustomDebugStringConvertible conformance

### ISSUE THREAD

**Issue by brentleyjones** [TabletopAssistant/DiceKit#50]
https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Swift_CustomDebugStringConvertible_Protocol/index.html#//apple_ref/swift/intfp/CustomDebugStringConvertible/s:vPSs28CustomDebugStringConvertible16debugDescriptionSS

**Comment by brentleyjones** [comment]
@JonathanHoffman I added the requirement for normal `CustomStringConvertible` conformance as well.

**Comment by JonathanHoffman** [comment]
ok!
