### ISSUE TITLE
Support subtraction of expressions

### ISSUE THREAD

**Issue by brentleyjones** [TabletopAssistant/DiceKit#63]
Needs to support:
- `-` binary operator for expressions
- `subtract` method for `FrequencyDistribution`
- Similar method on `ProbabilityMass` (I'm honestly not sure on the name yet)
- `CustomStringConvertible` conformance
- `0 - expression == -expression`

**Comment by JonathanHoffman** [comment]
`CustomStringLiteral` or `CustomStringConvertible`?

**Comment by brentleyjones** [comment]
Fixed.
